# TIME SERIES MODELS
## Forecasting 
## Smoothing/ETS


setwd("D:/UNH/SEMESTER 3/Business Forecastiing/class6")
options(digits = 3, scipen = 9999, stringasFactors = FALSE)
remove(list = ls())
graphics.off()

# Rev: September 2025

      #' A time series is an observation of a concept over time. The amount of
      #' rainfall in a region, the price of HD stock, the latest Consumer Sentiment
      #' Index are sequences of the same object ordered by time.  The objective is 
      #' model how this concept changes through time - and, presumably, where it is 
      #' headed.
      
      #' Time Series analysis is When we account for past observations of a 
      #' variable over time to appraise its behavior and project its 
      #' path into the future. 
      
      #' The methodology is to examine patterns in the past and use these structures
      #' to forecast. 


#Load libraries ======================

library(pdfetch)
library(forecast)
library(lubridate)
library(TSstudio)
library(tidyverse)
library(cowplot)
library(tsbox) #convert xts to tsibble
library(TSstudio)
library(rio)
library(forecast)
library(pdfetch)
library(quantmod)
library(tsibble)
library(dygraphs)
library(vars)


            # REFERENCES ==============
            # https://afit-r.github.io/ts_exploration

    #=======  #
    # Data =========
    
    ridership = read.csv("ridership.csv", stringsAsFactors = FALSE)
      head(ridership,3) ; tail(ridership,3)
      
    ridership$Ridership = ts(ridership$Ridership, start = c(1991,1), freq = 12)
        head(ridership)
        ts_info(ridership$Ridership)
      
    plot.ts(ridership$Ridership)
    ts_plot(ridership$Ridership)
    autoplot(ridership$Ridership)
    
    
    # Decompose ======
    # Trends induce positive correlations in the early lags.
    # Seasonality will induce peaks at the seasonal lags.
    
    mydecomp = stats::decompose(ridership$Ridership)
    
    plot(mydecomp)
  
          names(mydecomp)
          str(mydecomp)
          
      
    ts_plot(mydecomp$trend)
    ts_plot(mydecomp$seasonal)
    ts_plot(mydecomp$random)
        
    autoplot(ridership$Ridership) + 
      autolayer(mydecomp$trend) +
      autolayer(mydecomp$seasonal) +
      autolayer(mydecomp$random)
    
    autoplot(cbind(ridership$Ridership,mydecomp$trend, 
                   mydecomp$seasonal, mydecomp$random ))
    
    # split into training and testing
    length(ridership$Ridership)
    h = 30  #length of testing portion
    autoplot(ridership$Ridership)
    
    159-30
    
    split_ts_rider <- TSstudio::ts_split(ridership$Ridership, sample.out  = h)
    train_rider <- split_ts_rider$train
    test_rider <- split_ts_rider$test
    
    # Method: fit on train and test on test
    autoplot(train_rider) + autolayer(test_rider)
    ts_plot(cbind(train_rider, test_rider))
    
    #++++++++++++++
    #' A naive forecast uses the most recent observed data point as the 
    #' forecast for the next period; it assumes that the conditions and 
    #' patterns from the last period will continue unchanged. 
    
    #' It is a simple, inexpensive, and quick forecasting method. 
    #' However, it lacks accuracy because it doesn't account for trends, 
    #' seasonality, or other influencing factors.
    
    #' the naive forecast serves as a benchmark for evaluating the 
    #' effectiveness of more sophisticated forecasting models
    
    # Fit naive forecast
    fit <- naive(train_rider,h)
    fc = forecast(fit, h)
    autoplot(fc, PI = FALSE) + autolayer(train_rider) + autolayer(test_rider)
    
    ts_plot(cbind(fc$mean, train_rider, test_rider))
    forecast::accuracy(fit)
    
    
    #' A simple exponential smoothing (SES) forecast uses a weighted average of 
    #' past observations; to predict future values, it gives exponentially 
    #' more weight to recent data and less to older data. 
    
    #' It assumes there's no significant trend or seasonality. 
    #' The level of responsiveness to more recent data is controlled by 
    #' (alpha, α) a smoothing constant.
    #' A higher α makes the forecast more sensitive to recent change.
    
    # fit simple exponential smoothing
    fit <- ses(train_rider, h)
      summary(fit)
    fc = forecast(fit, h)
    autoplot(fc,PI = FALSE) + autolayer(train_rider) + autolayer(test_rider)
    ts_plot(cbind(fc$mean, train_rider, test_rider))
    forecast::accuracy(fit)
    
    #' Holt's method extends simple exponential smoothing by separately 
    #' modeling and smoothing both the level (current value) and 
    #' the trend (rate of change) of the data. 
    #' It works best with time series data that exhibits a trend but 
    #' no seasonal component.
    
    #' The forecast is generated by combining the smoothed level and 
    #' trend components, and it uses two smoothing parameters: alpha (α) 
    #' for the level and beta (β) for the trend.
    
        ndiffs(train_rider, test = "adf")
        tseries::adf.test(train_rider)
    
    # fit holt  (aka double exponential smoothing)
    fit = holt(train_rider)
      summary(fit)
    fc = forecast(fit, h)
    autoplot(fc, PI = FALSE) + autolayer(train_rider) + autolayer(test_rider)
    ts_plot(cbind(fc$mean, train_rider, test_rider))
    forecast::accuracy(fit)
    
    #' it is used to forecast a time series data that exhibits level, trend, 
    #' and seasonality components. 
    #' It enhances simpler exponential smoothing methods by adding a 
    #' third equation to account for seasonality (i.e. repeating, predictable 
    #' patterns) in the data, such as daily, weekly, or yearly fluctuations. 
    
    # fit holt winters (aka triple exponential smoothing)
    fit = hw(train_rider)
      summary(fit)
    fc = forecast(fit, h)
    autoplot(fc, PI = FALSE) + autolayer(train_rider) + autolayer(test_rider)
    ts_plot(cbind(fc$mean, train_rider, test_rider))
    forecast::accuracy(fit)
    
    
    # Error, Trend, Seasonality Model (ETS)
    #' ETS is a comprehensive framework that automatically selects the best 
    #' combination of error, trend, and seasonal components from 36 possible 
    #' models to fit a given time series. 
    
    # ets (more flexible)
    fit = ets(train_rider)
      summary(fit)
    fc = forecast(fit, h)
    autoplot(fc,PI = FALSE) + autolayer(train_rider) + autolayer(test_rider)
    ts_plot(cbind(fc$mean, train_rider, test_rider))
    forecast::accuracy(fit)
    
    
    #' MA calculates an average of past data points to predict future values, 
    #' The "moving" aspect entails a sliding window of data where 
    #' the oldest point is dropped and a new one is added as new data 
    #' becomes available.
    
    #' The moving average is best for short-term forecasting with relatively 
    #' stable demand and low order volumes where trends aren't 
    #' shifting dramatically.
    
    # fit a moving average
    fit = forecast::ma(train_rider,12, centre = FALSE)
    fc = forecast(fit, h)
    autoplot(fc, PI = FALSE) + autolayer(train_rider) + autolayer(test_rider)
    ts_plot(cbind(fc$mean, train_rider, test_rider))
    forecast::accuracy(fit)
    
    myma_t = zoo::rollmean(train_rider, k = 12, align = "right") # 12 month trailing
    autoplot(train_rider) + autolayer(myma_t)
    myfit = forecast(myma_t, h)
    autoplot(myfit, PI = FALSE) + autolayer(train_rider) + autolayer(test_rider)
    ts_plot(cbind(fc$mean, train_rider, test_rider))
    accuracy(myfit)
    #=======  #
    # ==========================  #
    ## Moving Average Forecast
    
    getSymbols("UMCSENT", src = "FRED", 
               freq = "monthly",
               return.class = "xts",
               from = "2010-01-01",
               to = Sys.Date()
    )
    
    sent = pdfetch_FRED("UMCSENT")
    
        sent = UMCSENT
    start(sent); end(sent)
    ts_info(sent)
    
    sent.ts = ts(sent, start = c(1952,11),freq = 12)
        ts_info(sent.ts)
    sent.ts = window(sent.ts, start = c(2010,1),end = c(2025,8))
    autoplot(sent.ts)
    
    
    #training and testing 
    h = 30
    split_ts_rider <- ts_split(sent.ts, sample.out  = h)
    train_rider <- split_ts_rider$train
    test_rider <- split_ts_rider$test
    
    myma_t = zoo::rollmean(train_rider, k = 12, align = "right") # 12 month trailing
          myma_t = forecast::ma(train_rider, 12, centre = FALSE) # trailing MA
          
    autoplot(train_rider) + autolayer(myma_t, linewidth = 2)
        
          
    #forecast with MA
    fit = zoo::rollmean(train_rider, k = 30, align = "right") # 12 month trailing
    fc = forecast(fit, h)
    autoplot(fc, PI = FALSE) + autolayer(train_rider) + autolayer(test_rider)
    
        forecast::accuracy(fc$fitted, train_rider)
  
    
    # ===================  #
    # IN Class or Homework =======
        
        
    #Problem 1
    #'Load the oil prices data, West Texas Intermediate, ticker = DCOILWTICO. 
    #'transform it the the ts type - using TSBox and plot it.
    
        
        # Problem 1: Load WTI (DCOILWTICO) from FRED, convert to ts, plot
        library(quantmod)      # getSymbols or use pdfetch
        library(pdfetch)       # you already used pdfetch in your script
        library(forecast)
        library(tsbox)
        library(lubridate)
        library(ggplot2)
        # --- Libraries ---
        library(pdfetch)
        library(zoo)
        library(ggplot2)
        
        # --- Fetch WTI data from FRED (daily spot price) ---
        wti <- pdfetch_FRED("DCOILWTICO")   # daily WTI spot price
        
        # --- Convert xts → zoo for aggregation ---
        wti_zoo <- zoo::as.zoo(wti)
        
        # --- Aggregate to monthly average ---
        wti_monthly <- aggregate(wti_zoo, 
                                 as.yearmon, 
                                 FUN = mean, na.rm = TRUE)
        
        # --- Convert to ts object ---
        wti_ts <- ts(wti_monthly,
                     start = c(as.numeric(format(start(index(wti_monthly)), "%Y")),
                               as.numeric(format(start(index(wti_monthly)), "%m"))),
                     frequency = 12)
        
        # --- Plot ---
        autoplot(wti_ts) +
          ggtitle("WTI (DCOILWTICO) — monthly average (ts)") +
          xlab("Year") +
          ylab("USD")
        
        
        
    # Problem 2
        #' Split sales into training and testing.  
        #' Plot the two series
        
        
        # Problem 2: assume series 'sales_ts' is already a ts object (monthly)
        # (Replace 'sales.csv' & column name as needed)
        
        sales_df <- read.csv("sales.csv", stringsAsFactors = FALSE)  # adjust filename
        # Example:
        sales_df$Sales <- ts(sales_df$Sales, start = c(2015,1), freq=12)
        sales_ts <- ts(sales_df$Sales, start = c(2015,1), freq = 12)
        
        h <- 30   # test length (same as your pattern)
        split_sales <- TSstudio::ts_split(sales_ts, sample.out = h)
        train_sales <- split_sales$train
        test_sales  <- split_sales$test
        
        # Plot train + test
        autoplot(train_sales) + autolayer(test_sales) + ggtitle("Train (solid) and Test (dashed)") + ylab("Sales")
        # or
        ts_plot
        
        
    #Problem 3
    #' Use the ses function from the forecast package to get a forecast 
    #' based on simple exponential smoothing fit of the training data, 
    #' plot the forecast and compare to the testing data.
    #' Plot all series
        
        
        # Problem 3: Simple exponential smoothing (SES)
        library(forecast)
        
        fit_ses <- ses(train_rider, h = h)
        fc_ses  <- forecast(fit_ses, h = h)
        
        # Plot forecast vs train/test
        autoplot(fc_ses, PI = FALSE) +
          autolayer(train_rider, series = "Train") +
          autolayer(test_rider, series = "Test") +
          ggtitle("SES Forecast vs Train and Test")
        
        # Accuracy
        acc_ses <- accuracy(fc_ses, test_rider)  # or accuracy(fc_ses$mean, test_rider)
        print(acc_ses)
        # RMSE is in acc_ses["Test set", "RMSE"] (or acc_ses[2,"RMSE"] depending on matrix)
        
    # Problem 4
    # Fit an exponential smoothing model using the ets function - again on the
        # training set
    #' Then pass the model as input to the forecast function to get a 
    #' forecast for the next h months, 
    #' and plot the forecast, testing and training sets.
    
        
        # Problem 4: ETS (automatic selection)
        fit_ets <- ets(train_rider)
        summary(fit_ets)
        
        fc_ets <- forecast(fit_ets, h = h)
        
        autoplot(fc_ets, PI = FALSE) +
          autolayer(train_rider, series = "Train") +
          autolayer(test_rider, series = "Test") +
          ggtitle("ETS Forecast vs Train & Test")
        
        # Accuracy
        acc_ets <- accuracy(fc_ets, test_rider)
        print(acc_ets)
        
        # Problem 5
    #' Fit a 12-month trailing moving average model on the training set.
    #' predict h periods above; plot all series.  the actual
    #' the training, the testing and the moving average prediction
        
        
        # Problem 5: 12-month trailing moving average forecast
        library(zoo)
        
        k <- 12
        ma_train <- zoo::rollmean(train_rider, k = k, align = "right", na.pad = FALSE)
        
        # Plot training series with rolling MA
        autoplot(train_rider) + autolayer(ts(ma_train, start = time(train_rider)[k], frequency = frequency(train_rider)),
                                          series = "12-mo MA", lwd = 1.2) +
          ggtitle("Train with 12-month trailing MA")
        
        # Use the last trailing MA value as constant forecast for next h periods
        last_ma <- as.numeric(tail(ma_train, 1))
        fc_ma_mean <- ts(rep(last_ma, h),
                         start = time(train_rider)[length(train_rider)] + deltat(train_rider),
                         frequency = frequency(train_rider))
        # Construct forecast object for plotting convenience
        fc_ma <- forecast::forecast(ts(c(train_rider), start = start(train_rider), frequency = frequency(train_rider)),
                                    h = h)
        fc_ma$mean <- fc_ma_mean
        
        autoplot(fc_ma, PI = FALSE) + autolayer(train_rider) + autolayer(test_rider) +
          ggtitle("Trailing 12-mo MA constant forecast vs Test")
        # Accuracy
        acc_ma <- accuracy(fc_ma$mean, test_rider)
        print(acc_ma)
        
    # Problem 6
    #' Print a summary of the model estimated in the previous exercise, 
    #' and find the automatically estimated structure of the model. 
    #' Does it include trend and seasonal components? 
        
        
        # Problem 6: Inspect ETS structure
        summary(fit_ets)
        
        # A short programmatic check:
        model_string <- fit_ets$method
        model_string  # e.g., "ETS(A,A,N)" or "ETS(A,A,A)"
        
        # Interpret:
        # - If model_string contains A or M in the second slot (trend slot), it includes trend (A = additive, M = multiplicative).
        # - If the third slot is A or M (seasonal slot), it includes seasonality; if it's "N" then no seasonality.
        
    # Problem 7
    #' Use the accuracy function from the forecast package to get accuracy 
    #' measures for the forecast obtained in the previous exercise. 
    #' Note the RMSE.
        
        # Problem 7: Collect accuracy metrics for the models you've fitted:
        acc_ses  <- accuracy(fc_ses, test_rider)    # SES
        acc_holt <- { fit_holt <- holt(train_rider, h = h); accuracy(forecast(fit_holt, h = h), test_rider) }  # Holt
        acc_hw   <- { fit_hw <- hw(train_rider, seasonal = "additive", h = h); accuracy(forecast(fit_hw, h = h), test_rider) } # Holt-Winters
        acc_ets  <- accuracy(fc_ets, test_rider)   # ETS
        acc_ma   <- accuracy(fc_ma$mean, test_rider) # MA constant forecast (vector)
        
        # Print a concise table of RMSEs
        rmse_table <- data.frame(
          Model = c("SES", "Holt", "HoltWinters(hw)", "ETS", "MA12-constant"),
          RMSE  = c(acc_ses["Test set","RMSE"],
                    acc_holt["Test set","RMSE"],
                    acc_hw["Test set","RMSE"],
                    acc_ets["Test set","RMSE"],
                    if(is.matrix(acc_ma)) acc_ma["Test set","RMSE"] else acc_ma[2,"RMSE"])
        )
        print(rmse_table)
        
        
        # Interpret:
        # - If model_string contains A or M in the second slot (trend slot), it includes trend (A = additive, M = multiplicative).
        # - If the third slot is A or M (seasonal slot), it includes seasonality; if it's "N" then no seasonality.
        
        
        # ===================  # 
        # Deliverable: fit a holt winters model
        # onto the training series.  
        # forecast onto the testing series
        # and plot all series.
        # Deliverable: Holt-Winters (triple exponential smoothing)
        library(forecast)
        
        # Automatic seasonal selection based on frequency. Use additive or multiplicative seasonality as appropriate.
        fit_hw <- hw(train_rider, seasonal = "additive", h = h)  # try "multiplicative" if seasonality appears multiplicative
        summary(fit_hw)
        
        # Forecast
        fc_hw <- forecast(fit_hw, h = h)
        
        # Plot
        p <- autoplot(fc_hw, PI = TRUE) +
          autolayer(train_rider, series = "Train") +
          autolayer(test_rider, series = "Test") +
          ggtitle("Holt-Winters Forecast vs Train & Test") +
          theme_minimal()
        
        print(p)
        
        # Save plot to file (PNG) — change path as needed:
        png(filename = "holtwinters_ridership.png", width = 1200, height = 700, res = 150)
        print(p)
        dev.off()
        
        # Accuracy on test:
        acc_hw <- accuracy(fc_hw, test_rider)
        print(acc_hw)
        
        # If you need to upload to a cloud bucket, use your preferred CLI or R package (aws.s3, googleCloudStorageR, etc.)
        # Example (AWS S3) using aws.s3:
        # library(aws.s3)
        # put_object(file = "holtwinters_ridership.png", object = "holtwinters/holtwinters_ridership.png", bucket = "your-bucket-name")
        compare <- rbind(
          cbind(Model = "SES",  t(accuracy(fc_ses, test_rider)[2, c("ME","RMSE","MAE","MAPE")])),
          cbind(Model = "Holt", t(acc_holt[2, c("ME","RMSE","MAE","MAPE")])),
          cbind(Model = "HW",   t(acc_hw[2, c("ME","RMSE","MAE","MAPE")])),
          cbind(Model = "ETS",  t(acc_ets[2, c("ME","RMSE","MAE","MAPE")])),
          cbind(Model = "MA12", t(acc_ma[2, c("ME","RMSE","MAE","MAPE")]))
        )
        as.data.frame(compare)
        
        
        
        # Upload the graph to the bucket labeled holtwinters.
        # by Friday October 24.
        # ===================  # 
        
        